#!/usr/bin/env bash
# One-time server provisioning for the HS Property Management box.
# Idempotent: safe to re-run.
set -euo pipefail

APP_DIR=/opt/haspm
REPO=https://github.com/princewizl/haspm.git

echo "==> Packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl git ufw fail2ban unattended-upgrades

echo "==> Docker"
if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
                         docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
fi
docker --version
docker compose version

echo "==> Firewall"
ufw allow OpenSSH        >/dev/null
ufw allow 80/tcp         >/dev/null
ufw allow 443/tcp        >/dev/null
ufw --force enable       >/dev/null
ufw status verbose | head -12

echo "==> fail2ban"
systemctl enable --now fail2ban >/dev/null 2>&1 || true

echo "==> Application directory"
if [ ! -d "$APP_DIR/.git" ]; then
  git clone "$REPO" "$APP_DIR"
else
  git -C "$APP_DIR" remote set-url origin "$REPO"
fi

# Persistent state. uid 10001 matches the hsapp user in the image.
mkdir -p "$APP_DIR"/data/{live,test}/{data,static-uploads/properties,doc-uploads/documents}
chown -R 10001:10001 "$APP_DIR/data"

echo "==> Environment files"
gen_env () {
  local file="$1" env_name="$2"
  if [ -f "$file" ]; then
    echo "    $file already exists — left untouched"
    return
  fi
  cat > "$file" <<EOF
# Generated by bootstrap-server.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
APP_ENV=${env_name}
SECRET_KEY=$(openssl rand -hex 32)
EOF
  chmod 600 "$file"
  echo "    wrote $file"
}
gen_env "$APP_DIR/.env.live" live
gen_env "$APP_DIR/.env.test" test

echo
echo "Bootstrap complete."
echo "Next:  $APP_DIR/deploy/issue-certs.sh      (once DNS is pointing here)"
echo "Then:  $APP_DIR/deploy/deploy.sh all"
